#!/usr/bin/ruby

# ERROR CODES
#
# 1 - unknown error
# 2 - unsupported OS
# 3 - missing dependacy (such as git)

FLASH_VERSIONS = [
  { :name => "Flash CS4", :directory => "#{ENV['HOME']}/Library/Application Support/Adobe/Flash CS4/en/Configuration/Commands" },
  { :name => "Flash CS5", :directory => "#{ENV['HOME']}/Library/Application Support/Adobe/Flash CS5/en_US/Configuration/Commands" },
  { :name => "Flash CS5.5", :directory => "#{ENV['HOME']}/Library/Application Support/Adobe/Flash CS5.5/en_US/Configuration/Commands" },
  { :name => "Flash CS6", :directory => "#{ENV['HOME']}/Library/Application Support/Adobe/Flash CS6/en_US/Configuration/Commands" }
]

unless RUBY_PLATFORM.include?("darwin")
  puts "Unable to update. This update script currently only supports OS X."
  exit 2
end

# # TODO: Check is git is installed.
# begin
#   %x[git > /dev/null]
# rescue
#   puts "Unable to install. Couldn't find Git. http://git-scm.com/"
#   exit 3
# end

FLASH_VERSIONS.each do |flash_version|
  if File.directory?("#{flash_version[:directory]}/Katalyst")
    puts "Updating #{flash_version[:name]} installation..."
    Dir.chdir("#{flash_version[:directory]}/Katalyst")
    `git pull > /dev/null`
    puts "Complete."
  else
    puts "No installation for #{flash_version[:name]} found."
  end
end

exit 0
